services:
  pc1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pc1
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - redlocal

  pc2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pc2
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - redlocal

  pc3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pc3
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - redlocal
networks:
  redlocal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
